basePath: /
host: localhost:9093
info:
  contact:
    email: support@swagger.io
    name: API Support - Blockchain Wadzpay
    url: http://www.swagger.io/support
  description: This is a sample wadzpay project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Wadzpay go API
  version: "1.0"
paths:
  /createalgoaccount:
    get:
      consumes:
      - application/json
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create a new algo account.
      tags:
      - root
  /pagoentities:
    get:
      consumes:
      - application/json
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the status of server.
      tags:
      - root
  /pagotoken:
    get:
      consumes:
      - application/json
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Show the status of server.
      tags:
      - root
schemes:
- http
swagger: "2.0"
